# CMake generated Testfile for 
# Source directory: E:/work/Whateley/eeagl/lib/cereal-1.2.2/unittests
# Build directory: E:/work/Whateley/eeagl/lib/cereal-1.2.2/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_array "test_array")
add_test(test_basic_string "test_basic_string")
add_test(test_bitset "test_bitset")
add_test(test_boost_variant "test_boost_variant")
add_test(test_chrono "test_chrono")
add_test(test_complex "test_complex")
add_test(test_deque "test_deque")
add_test(test_forward_list "test_forward_list")
add_test(test_list "test_list")
add_test(test_load_construct "test_load_construct")
add_test(test_map "test_map")
add_test(test_memory "test_memory")
add_test(test_memory_cycles "test_memory_cycles")
add_test(test_multimap "test_multimap")
add_test(test_multiset "test_multiset")
add_test(test_pair "test_pair")
add_test(test_pod "test_pod")
add_test(test_polymorphic "test_polymorphic")
add_test(test_portable_binary_archive "test_portable_binary_archive")
add_test(test_priority_queue "test_priority_queue")
add_test(test_queue "test_queue")
add_test(test_set "test_set")
add_test(test_stack "test_stack")
add_test(test_structs "test_structs")
add_test(test_structs_minimal "test_structs_minimal")
add_test(test_structs_specialized "test_structs_specialized")
add_test(test_tuple "test_tuple")
add_test(test_unordered_loads "test_unordered_loads")
add_test(test_unordered_map "test_unordered_map")
add_test(test_unordered_multimap "test_unordered_multimap")
add_test(test_unordered_multiset "test_unordered_multiset")
add_test(test_unordered_set "test_unordered_set")
add_test(test_user_data_adapters "test_user_data_adapters")
add_test(test_valarray "test_valarray")
add_test(test_vector "test_vector")
add_test(test_versioning "test_versioning")
add_test(test_cmake_config_module "C:/Program Files (x86)/CMake/bin/cmake.exe" "-P" "E:/work/Whateley/eeagl/lib/cereal-1.2.2/unittests/cmake-config-module.cmake")
